# Generated by Django 5.1.1 on 2025-02-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EC', models.IntegerField(default=0)),
                ('OR', models.IntegerField(default=0)),
                ('CA', models.IntegerField(default=0)),
                ('EA', models.IntegerField(default=0)),
                ('estilo_predominante', models.CharField(blank=True, max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
