# Generated by Django 5.1.1 on 2025-02-23 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kolb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('dimension', models.CharField(choices=[('EC', 'Experiencia Concreta'), ('OR', 'Observación Reflexiva'), ('CA', 'Conceptualización Abstracta'), ('EA', 'Experimentación Activa')], max_length=2)),
                ('orden', models.PositiveIntegerField(unique=True)),
            ],
        ),
    ]
