# Generated by Django 5.1.1 on 2025-02-23 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kolb', '0002_pregunta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='CA',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='EA',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='EC',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='OR',
        ),
        migrations.AddField(
            model_name='respuesta',
            name='respuestas',
            field=models.JSONField(default=dict),
        ),
    ]
